name: CI/CD Deployment

on:
  push:
    branches:
      - personalLaptop  # Adjust this as necessary for your workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VPS
      run: ssh -vvv ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd ~/RecipeShop && git pull"