name: CI/CD Deployment

on:
  push:
    branches:
      - main # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Git Pull in VPS
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/robin
          chmod 600 ~/.ssh/robin
          ssh-keyscan -H 219.93.129.19 >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: ssh -i ~/.ssh/robin server@219.93.129.19 "cd /RecipeShop && git pull"
